repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black"]

    - repo: https://github.com/myint/autoflake
      rev: v2.0.1
      hooks:
          - id: autoflake
            args:
                - --in-place
                - --remove-unused-variables
                - --remove-all-unused-imports
                - --expand-star-imports
                - --ignore-init-module-imports

    - repo: https://github.com/myint/eradicate
      rev: v2.1.0
      hooks:
          - id: eradicate
            args:
              - --in-place

    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.4'
      hooks:
        - id: bandit
          args: ["-x", "tests/*"]

    - repo: local
      hooks:
      - id: pytest-check
        name: pytest-check
        stages: [commit]
        types: [python]
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
