name: Process latest city influence deposits & set new city capital

on:
  # schedule:
  # - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  process_deposits:
    name: Run city influence worker
    runs-on: ubuntu-latest
    env:
      MANAGER_PASSPHRASE: ${{ secrets.MANAGER_PASSPHRASE }}
      LEDGER_TYPE: ${{ secrets.LEDGER_TYPE }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.9

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.1.5
      with:
          poetry-version: 1.1.6

    - name: Install python dependencies
      run: poetry install

    - uses: pre-commit/action@v3.0.0
      name: "Linters and formatters check"
      with:
        extra_args: --all-files --show-diff-on-failure

    - name: Create local changes
      run: |
        PYTHONPATH="." poetry run python src/city_rewards_worker.py

    - name: Commit files
      run: |
        git config --local user.email "millionalgos@pm.me"
        git config --local user.name "github-actions[bot]"
        git commit -m "🤖 Refreshed city influence related data" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
